name: Run Market Monitor

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'analysis_report.md'
      - 'market_monitor.py'
      - '.github/workflows/run_market_monitor.yml'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 50  # 整体超时 50 分钟

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clear cache
        run: |
          rm -rf $GITHUB_WORKSPACE/.cache
          echo "Cache cleared"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pandas==2.1.4 numpy requests beautifulsoup4 lxml
          python -c "import pandas, numpy, requests, bs4, lxml; import pkg_resources; print(f'Pandas: {pkg_resources.get_distribution(\"pandas\").version}, Requests: {pkg_resources.get_distribution(\"requests\").version}')"

      - name: Verify files exist
        run: |
          set -e
          if [ ! -f analysis_report.md ]; then
            echo "Error: analysis_report.md not found!"
            exit 1
          fi
          if [ ! -f market_monitor.py ]; then
            echo "Error: market_monitor.py not found!"
            exit 1
          fi
          echo "Required files found: analysis_report.md, market_monitor.py"
          echo "Contents of analysis_report.md (first 1000 characters):"
          head -c 1000 analysis_report.md

      - name: Verify market_monitor.py does not use akshare or selenium
        run: |
          if grep -q -i "akshare" market_monitor.py || grep -q "selenium" market_monitor.py || grep -q "fund_open_fund_info_em" market_monitor.py; then
            echo "Error: market_monitor.py contains akshare, selenium or fund_open_fund_info_em references!"
            exit 1
          fi
          echo "market_monitor.py does not contain disallowed references."

      - name: Run Market Monitor script
        run: |
          timeout 180 python market_monitor.py || { echo "Script timed out or failed, check market_monitor.log"; cat market_monitor.log 2>/dev/null || echo "No log file generated"; exit 1; }  # 3分钟超时

      - name: Check generated files
        run: |
          echo "Checking generated files:"
          ls -l market_monitor_report.md market_monitor.log 2>/dev/null || echo "Some files may not exist"
          if [ -f market_monitor_report.md ]; then
            echo "Contents of market_monitor_report.md:"
            cat market_monitor_report.md
          fi
          if [ -f market_monitor.log ]; then
            echo "Contents of market_monitor.log:"
            cat market_monitor.log
          fi

      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add --all
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update market monitor report and log - $(date)"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Check for errors in log
        if: always()
        run: |
          if [ -f market_monitor.log ]; then
            echo "Full log content:"
            cat market_monitor.log
            if grep -i "ERROR" market_monitor.log; then
              echo "Errors found in log:"
              grep -i "ERROR" market_monitor.log
              exit 1
            else
              echo "No errors found in log. Success!"
            fi
          else
            echo "market_monitor.log not found. Workflow may have failed at an earlier step."
            exit 1
          fi
