name: Run Market Monitor

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'analysis_report.md'
      - 'market_monitor.py'
      - '.github/workflows/run_market_monitor.yml'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 增加超时时间以适应翻页

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clear cache
        run: |
          rm -rf $GITHUB_WORKSPACE/.cache
          echo "Cache cleared"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip fontconfig locales libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc-s1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libnss3 libayatana-appindicator3-1
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas numpy tenacity requests webdriver-manager

      - name: Run Market Monitor script
        run: |
          python market_monitor.py
        env:
          PYTHONIOENCODING: utf-8
        continue-on-error: true

      - name: Display generated reports and logs
        if: always()
        run: |
          echo "Generated Report Content:"
          if [ -f market_monitor_report.md ]; then
            cat market_monitor_report.md
          else
            echo "market_monitor_report.md not found."
          fi
          echo "---"
          echo "Log Content:"
          if [ -f market_monitor.log ]; then
            cat market_monitor.log
          else
            echo "market_monitor.log not found."
          fi
          
          echo "---"
          echo "Debug files (if any):"
          if ls debug_page_*.html 2>/dev/null; then
            echo "Sample debug page content (first 1000 chars of first file):"
            head -c 1000 debug_page_*.html | head -n 1
          fi
          if ls error_page_*.html 2>/dev/null; then
            echo "Sample error page content (first 1000 chars of first file):"
            head -c 1000 error_page_*.html | head -n 1
          fi

      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add market_monitor_report.md market_monitor.log # 添加日志文件
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update market monitor report and log - $(date)"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Check for errors in log
        if: always()
        run: |
          if [ -f market_monitor.log ]; then
            echo "Full log content:"
            cat market_monitor.log
            if grep -i "ERROR" market_monitor.log; then
              echo "Errors found in log:"
              grep -i "ERROR" market_monitor.log
              exit 1
            else
              echo "No errors found in log. Success!"
            fi
          else
            echo "market_monitor.log not found. Cannot check for errors."
          fi
